export function generateRepositoryMap(model, tokenBudget) {
  const heading = [
    "# Repository Map",
    "",
    "_Generated by `ai-context sync`. Read this before opening source files._",
    "",
  ];
  const lines = [...heading];
  let includedFiles = 0;

  for (const file of model.files) {
    const detail = file.symbols.length > 0
      ? `- \`${file.path}\`: ${file.symbols.join(", ")}`
      : `- \`${file.path}\``;
    const prospectiveFooter = footer(includedFiles + 1, model.files.length, tokenBudget);
    const prospective = [...lines, detail, "", prospectiveFooter, ""].join("\n");
    if (estimateTokens(prospective) > tokenBudget) continue;
    lines.push(detail);
    includedFiles += 1;
  }

  const provisionalFooter = footer(includedFiles, model.files.length, tokenBudget);
  const estimatedTokens = estimateTokens([...lines, "", provisionalFooter, ""].join("\n"));
  lines.push(
    "",
    footer(includedFiles, model.files.length, tokenBudget, estimatedTokens),
    "",
  );

  return {
    content: lines.join("\n"),
    estimatedTokens,
    includedFiles,
  };
}

export function estimateTokens(text) {
  return Math.ceil(Buffer.byteLength(text, "utf8") / 4);
}

function footer(includedFiles, totalFiles, tokenBudget, estimatedTokens = tokenBudget) {
  return `Included ${includedFiles} of ${totalFiles} files within an estimated ${estimatedTokens}/${tokenBudget} token budget.`;
}
