export function generateSummary(model, repositoryMap, config = {}) {
  const languages = model.stack.languages.length
    ? model.stack.languages.map((item) => `${item.name} (${item.fileCount})`).join(", ")
    : "not detected";
  const frameworks = model.stack.frameworks.join(", ") || "not detected";
  const runtimes = model.stack.runtimes?.length
    ? model.stack.runtimes.map((item) => `${item.name} ${item.version}`).join(", ")
    : "not declared";
  const apm = config.apm?.enabled
    ? `${config.apm.provider} (${config.apm.serviceName || "service name not set"}, ${config.apm.environment || "environment not set"})`
    : "disabled";
  const economy = repositoryMap.tokenEconomy;

  return [
    "# Project Summary",
    "",
    "_Generated by `ai-context sync`._",
    "",
    `- Languages: ${languages}`,
    `- Runtime versions: ${runtimes}`,
    `- Frameworks/tooling: ${frameworks}`,
    `- APM context: ${apm}`,
    `- Scanned files: ${model.statistics.files}`,
    `- Discovered symbols: ${model.statistics.symbols}`,
    `- Repository map files: ${repositoryMap.includedFiles}`,
    `- Estimated map tokens: ${repositoryMap.estimatedTokens}`,
    "",
    "## Estimated token economy",
    "",
    `- Full scanned source: ~${economy.estimatedSourceTokens} tokens (${economy.sourceBytes} bytes)`,
    `- Compact repository map: ~${economy.compactMapTokens} tokens`,
    `- Tokens avoided per full-context pass: ~${economy.estimatedTokensSaved}`,
    `- Estimated reduction: ${economy.reductionPercent}%`,
    `- Compression ratio: ${economy.compressionRatio}:1`,
    `- Token budget used: ${economy.budgetUtilizationPercent}%`,
    "",
    "_Token counts use the deterministic UTF-8 bytes / 4 estimate; provider tokenizers may differ._",
    "",
    "Start with `../memory/project-memory.md`, then read this summary and",
    "`../indexes/repository-map.md`.",
    "Open source files only when the map points to relevant code.",
    "",
  ].join("\n");
}

export function generateMachineSummary(model, repositoryMap, config = {}) {
  return `${JSON.stringify({
    schemaVersion: 3,
    stack: model.stack,
    apm: publicApmConfig(config.apm),
    statistics: model.statistics,
    repositoryMap: {
      includedFiles: repositoryMap.includedFiles,
      estimatedTokens: repositoryMap.estimatedTokens,
    },
    tokenEconomy: repositoryMap.tokenEconomy,
    files: model.files.map(({ path, bytes, symbols }) => ({ path, bytes, symbols })),
  }, null, 2)}\n`;
}

function publicApmConfig(apm = {}) {
  return {
    enabled: apm.enabled === true,
    provider: apm.provider || "generic",
    serviceName: apm.serviceName || "",
    environment: apm.environment || "",
    dashboardUrl: apm.dashboardUrl || "",
  };
}
