export function generateSummary(model, repositoryMap) {
  const languages = model.stack.languages.length
    ? model.stack.languages.map((item) => `${item.name} (${item.fileCount})`).join(", ")
    : "not detected";
  const frameworks = model.stack.frameworks.join(", ") || "not detected";

  return [
    "# Project Summary",
    "",
    "_Generated by `ai-context sync`._",
    "",
    `- Languages: ${languages}`,
    `- Frameworks/tooling: ${frameworks}`,
    `- Scanned files: ${model.statistics.files}`,
    `- Discovered symbols: ${model.statistics.symbols}`,
    `- Repository map files: ${repositoryMap.includedFiles}`,
    `- Estimated map tokens: ${repositoryMap.estimatedTokens}`,
    "",
    "Start with `project.md`, then read this summary and `repository-map.md`.",
    "Open source files only when the map points to relevant code.",
    "",
  ].join("\n");
}

export function generateMachineSummary(model, repositoryMap) {
  return `${JSON.stringify({
    schemaVersion: 1,
    stack: model.stack,
    statistics: model.statistics,
    repositoryMap: {
      includedFiles: repositoryMap.includedFiles,
      estimatedTokens: repositoryMap.estimatedTokens,
    },
    files: model.files.map(({ path, bytes, symbols }) => ({ path, bytes, symbols })),
  }, null, 2)}\n`;
}
